export const dataSkill = [
  {
    name: '인기',
    value: [
      { img: '/img/javascript.svg', item: 'JavaScript' },
      { img: '/img/typescript.svg', item: 'TypeScript' },
      { img: '/img/react.svg', item: 'React' },
      { img: '/img/vue.svg', item: 'Vue' },
      { img: '/img/svelte.svg', item: 'Svelte' },
      { img: '/img/nextjs.svg', item: 'NextJs' },
      { img: '/img/nodejs.svg', item: 'NodeJs' },
      { img: '/img/java.svg', item: 'Java' },
      { img: '/img/spring.svg', item: 'Spring' },
      { img: '/img/go.svg', item: 'Go' },
    ],
  },
  {
    name: '프론트엔드',
    value: [
      { img: '/img/javascript.svg', item: 'JavaScript' },
      { img: '/img/typescript.svg', item: 'TypeScript' },
      { img: '/img/react.svg', item: 'React' },
      { img: '/img/vue.svg', item: 'Vue' },
      { img: '/img/nextjs.svg', item: 'NextJs' },
      { img: '/img/svelte.svg', item: 'Svelte' },
    ],
  },
  {
    name: '백엔드',
    value: [
      { img: '/img/java.svg', item: 'Java' },
      { img: '/img/spring.svg', item: 'Spring' },
      { img: '/img/nodejs.svg', item: 'NodeJs' },
      { img: '/img/nestjs.svg', item: 'NestJs' },
      { img: '/img/go.svg', item: 'Go' },
      { img: '/img/kotlin.svg', item: 'Kotlin' },
      { img: '/img/express.svg', item: 'Express' },
      { img: '/img/mysql.svg', item: 'MySQL' },
      { img: '/img/mongodb.svg', item: 'MongoDB' },
      { img: '/img/python.svg', item: 'Python' },
      { img: '/img/django.svg', item: 'Django' },
      { img: '/img/php.svg', item: 'PHP' },
      { img: '/img/graphql.svg', item: 'GraphQL' },
      { img: '/img/firebase.svg', item: 'FireBase' },
    ],
  },
  {
    name: '모바일',
    value: [
      { img: '/img/flutter.svg', item: 'Flutter' },
      { img: '/img/swift.svg', item: 'Swift' },
      { img: '/img/kotlin.svg', item: 'Kotlin' },
      { img: '/img/reactnative.svg', item: 'ReactNative' },
      { img: '/img/unity.svg', item: 'Unity' },
    ],
  },
  {
    name: '기타',
    value: [
      { img: '/img/aws.svg', item: 'AWS' },
      { img: '/img/kubernetes.svg', item: 'Kubernetes' },
      { img: '/img/docker.svg', item: 'Docker' },
      { img: '/img/git.svg', item: 'Git' },
      { img: '/img/figma.svg', item: 'Figma' },
      { img: '/img/zeplin.svg', item: 'Zeplin' },
      { img: '/img/jest.svg', item: 'Jest' },
      { img: '/img/c.svg', item: 'C' },
    ],
  },
  {
    name: '모두보기',
    value: [
      { img: '/img/javascript.svg', item: 'JavaScript' },
      { img: '/img/typescript.svg', item: 'TypeScript' },
      { img: '/img/react.svg', item: 'React' },
      { img: '/img/vue.svg', item: 'Vue' },
      { img: '/img/nextjs.svg', item: 'NextJs' },
      { img: '/img/svelte.svg', item: 'Svelte' },
      { img: '/img/java.svg', item: 'Java' },
      { img: '/img/spring.svg', item: 'Spring' },
      { img: '/img/nodejs.svg', item: 'NodeJs' },
      { img: '/img/nestjs.svg', item: 'NestJs' },
      { img: '/img/go.svg', item: 'Go' },
      { img: '/img/kotlin.svg', item: 'Kotlin' },
      { img: '/img/express.svg', item: 'Express' },
      { img: '/img/mysql.svg', item: 'MySQL' },
      { img: '/img/mongodb.svg', item: 'MongoDB' },
      { img: '/img/python.svg', item: 'Python' },
      { img: '/img/django.svg', item: 'Django' },
      { img: '/img/php.svg', item: 'PHP' },
      { img: '/img/graphql.svg', item: 'GraphQL' },
      { img: '/img/firebase.svg', item: 'FireBase' },
      { img: '/img/flutter.svg', item: 'Flutter' },
      { img: '/img/swift.svg', item: 'Swift' },
      { img: '/img/kotlin.svg', item: 'Kotlin' },
      { img: '/img/reactnative.svg', item: 'ReactNative' },
      { img: '/img/unity.svg', item: 'Unity' },
      { img: '/img/aws.svg', item: 'AWS' },
      { img: '/img/kubernetes.svg', item: 'Kubernetes' },
      { img: '/img/docker.svg', item: 'Docker' },
      { img: '/img/git.svg', item: 'Git' },
      { img: '/img/figma.svg', item: 'Figma' },
      { img: '/img/zeplin.svg', item: 'Zeplin' },
      { img: '/img/jest.svg', item: 'Jest' },
      { img: '/img/c.svg', item: 'C' },
    ],
  },
];
